### ISSUE TITLE
Improve installation process

### ISSUE THREAD

**Issue by liberostelios** [Artelia/NIMPHS#14]
### Description

As things stand, there is a lot of manual work required by the user to install the python dependencies and enough knowledge to understand  "where python is installed in Blender", as described in the documentation. Unfortunately, this is part of the inevitable complexity of using Blender. I've had a similar issue when trying to use `pyvista` for a QGIS plugin and I tried to solve it by running the necessary python commands from inside QGIS the first time (see [here](https://github.com/liberostelios/qgis-3d-toolbox/blob/main/processing/system/install_pyvista_algorithm.py)).

This might not be the most elegant or robust solution, but it works. Maybe you could try to implement something similar when Blender loads the plugin for the first time and only fall back to the manual installation if this fails.

**Comment by bnase** [comment]
I agree with @liberostelios . Moreover, at least for now, you should add that it _might require elevated access_ command prompt when installing the Python packages!

**Comment by Failxxx** [comment]
Thank you very much for your recommendations. I find your idea relevant in this case because indeed, a lot of work has to be done by the user before being able to use the add-on. I have been dealing with this issue for a long time, even for other add-ons I have made, but never thought the it could be possible to proceed like you suggest. I will definitely give it a try!

I will also add what you are pointing out @bnase. This will motivate me to deal with #12 haha.
